STD_ERR: 0.0001
VMC_NCONFIG: 100000
MOLECULES: ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'P', 'Cl', 'Ar']
MOLECULES: ['K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr']
METHODS: ['HartreeFock']
BASES: ['DZ', 'TZP', 'TZ2P', 'QZ4P']
JASTROWS: ['8_8_44']
