STD_ERR: 0.0001
VMC_NCONFIG: 100000
MOLECULES: ['Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe']
METHODS: ['HartreeFock']
BASES: ['ZORA_DZ', 'ZORA_TZP', 'ZORA_TZ2P', 'ZORA_QZ4P']
JASTROWS: ['8_8_44']
