STD_ERR: 0.0001
VMC_NCONFIG: 100000
#MOLECULES: ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'P', 'Cl', 'Ar']
#MOLECULES: ['K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr']
METHODS: ['HartreeFock']
#BASES: ['DZ', 'TZP', 'TZ2P', 'QZ4P']
BASES: ['QZ4P']
#MOLECULES: ['Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe']
MOLECULES: ['O3']
#BASES: ['ZORA_DZ', 'ZORA_TZP', 'ZORA_TZ2P', 'ZORA_QZ4P']
JASTROWS: ['8_8_44']
